name: Sync Fork
on:
  schedule:
   - cron: '0 22 * * *'
   - cron: '0 10 * * *' # 每天触发两次，可根据项目更新频率调整
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: qist # fork 的上游仓库 user
          head: master # fork 的上游仓库 branch
          base: master # 本地仓库 branch
