name: 自动同步上游仓库代码


on:
  schedule:
    - cron: '0 3 * * *'


jobs:
  sync-upstream:
   
    runs-on: ubuntu-latest

   
    steps:
     
      - name: 检出当前仓库代码
        uses: actions/checkout@v3
        with:
         
          persist-credentials: false
        
          submodules: true
         
          ref: master

     
      - name: 同步上游仓库更改
        uses: TG908/fork-sync@v1.7.3 
        with:
         
          upstream_repository: https://github.com/qist/tvbox.git
         
          upstream_branch: master
         
          target_branch: master
          # GitHub令牌，用于认证和访问仓库
          github_token: ${{ secrets.GITHUB_TOKEN }}
